[project]
name = "pydantic-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "pydantic[email]>=2.10.6",
    "pydantic-settings>=2.8.0",
]
